name: Continues testing

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KBUILD_BUILD_USER: NATO66613
      KBUILD_BUILD_HOST: KREMLIN
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true
          key: kernel-build-cache
          restore-keys: |
            kernel-build-cache
          max-size: '10G'

      - name: Restore toolchain cache
        id: restore-clang
        uses: actions/cache/restore@v4
        with:
          path: /home/runner/r547379
          key: clang-r547379

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex libelf-dev libncurses-dev libssl-dev unzip zip wget libarchive-tools
          ccache --show-stats

      - name: Deploy Clang
        if: steps.restore-clang.outputs.cache-hit != 'true'
        run: |
          git clone https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r547379.git /home/runner/r547379 --depth=1

      - name: Save clang
        if: steps.restore-clang.outputs.cache-hit != 'true'
        id: cache-clang-save
        uses: actions/cache/save@v4
